set(_AMENT_PACKAGE_NAME "ros2_controllers_interfaces")
set(ros2_controllers_interfaces_VERSION "0.0.1")
set(ros2_controllers_interfaces_MAINTAINER "Jerome Justin <j.justin@acfr.usyd.edu.au>")
set(ros2_controllers_interfaces_BUILD_DEPENDS "builtin_interfaces" "rosidl_default_generators" "std_msgs" "geometry_msgs")
set(ros2_controllers_interfaces_BUILDTOOL_DEPENDS "ament_cmake")
set(ros2_controllers_interfaces_BUILD_EXPORT_DEPENDS "std_msgs" "geometry_msgs")
set(ros2_controllers_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(ros2_controllers_interfaces_EXEC_DEPENDS "builtin_interfaces" "rosidl_default_runtime" "std_msgs" "geometry_msgs")
set(ros2_controllers_interfaces_TEST_DEPENDS )
set(ros2_controllers_interfaces_GROUP_DEPENDS )
set(ros2_controllers_interfaces_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(ros2_controllers_interfaces_DEPRECATED "")
set(ros2_controllers_interfaces_EXPORT_TAGS)
list(APPEND ros2_controllers_interfaces_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
