set(_AMENT_PACKAGE_NAME "swerve_controller")
set(swerve_controller_VERSION "0.0.1")
set(swerve_controller_MAINTAINER "Jerome Justin <jclinton830@gmail.com>")
set(swerve_controller_BUILD_DEPENDS "generate_parameter_library" "backward_ros" "control_msgs" "controller_interface" "ros2_controllers_interfaces" "geometry_msgs" "hardware_interface" "nav_msgs" "pluginlib" "rclcpp" "rclcpp_lifecycle" "realtime_tools" "rcpputils" "std_srvs" "tf2" "tf2_msgs" "tf2_geometry_msgs" "visualization_msgs")
set(swerve_controller_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(swerve_controller_BUILD_EXPORT_DEPENDS "backward_ros" "control_msgs" "controller_interface" "ros2_controllers_interfaces" "geometry_msgs" "hardware_interface" "nav_msgs" "pluginlib" "rclcpp" "rclcpp_lifecycle" "realtime_tools" "rcpputils" "std_srvs" "tf2" "tf2_msgs" "tf2_geometry_msgs" "visualization_msgs")
set(swerve_controller_BUILDTOOL_EXPORT_DEPENDS )
set(swerve_controller_EXEC_DEPENDS "backward_ros" "control_msgs" "controller_interface" "ros2_controllers_interfaces" "geometry_msgs" "hardware_interface" "nav_msgs" "pluginlib" "rclcpp" "rclcpp_lifecycle" "realtime_tools" "rcpputils" "std_srvs" "tf2" "tf2_msgs" "tf2_geometry_msgs" "visualization_msgs")
set(swerve_controller_TEST_DEPENDS "ament_cmake_gmock" "controller_manager")
set(swerve_controller_GROUP_DEPENDS )
set(swerve_controller_MEMBER_OF_GROUPS )
set(swerve_controller_DEPRECATED "")
set(swerve_controller_EXPORT_TAGS)
list(APPEND swerve_controller_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
